[package]
name = "server"
version = "0.1.0"
authors = ["Michael Lazear <lazear@scripps.edu>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rocket = "0.4"
rocket_codegen = "0.4"
rocket_contrib = "0.4"